name: build docker image

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We use setuptools-scm to do versioning, and it needs a full clone
          fetch-depth: "0"

      - name: Figure out docker image tag
        id: taggen
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/yuvipanda/z2jh-hub-with-fancy-profiles
          tags: |
            prefix=z2jh-v3.2.1-fancy-profiles-sha-,type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        # Run this only on merge
        if: "${{ github.event_name == 'push' }}"
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: "${{ github.event_name == 'push' }}"
          tags: ${{ steps.taggen.outputs.tags }}

      - name: Image Tag
        run: echo ${{ steps.taggen.outputs.tags }}
